'use strict';(function(Q){function q(a,b,c){this.width=a;this.height=b;this.canvas=window.document.createElement("canvas");this.canvas.width=a;this.canvas.height=b;switch(c[1]){case 0:this.u=null;this.sa=L.sb(this.canvas);break;case 1:this.u=this.canvas.getContext("2d",null),this.sa=null}}function z(a){this.m=a}function F(a,b){this.nb=a;this.ob=b;this.Ma=!1}function G(){this.Y=this.X=this.ja=this.ia=0;this.qa=this.ha=this.La=!1;this.W=this.V=this.ea=this.da=this.P=0;this.ca=this.Ka=!1;this.O=0;this.za=
this.pa=!1}function H(){this.images=[]}function L(){}function f(){}function l(a){this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,l)}function A(){this.K={}}function I(){}function x(a,b){n.call(this,a,b);this.dir=0;this.M=5*Math.random()|0}function J(a,b){this.i=a;this.K=b;this.data=[];this.J=[];for(var c=this.count=0;c<b;){var d=c++;this.data.push([]);for(var e=0;e<a;){var g=e++;this.data[d][g]=d&&g&&d!=a-1&&g!=b-1?.2>Math.random()?1:0:2}}this.data[a+2>>1][b+2>>1]=3;for(c=
0;c<b;)for(d=c++,e=0;e<a;)g=e++,0==this.data[d][g]&&.2>Math.random()&&this.I(new v(g,d));for(c=0;c<b;)for(d=c++,e=0;e<a;)g=e++,1==this.data[d][g]&&.5>Math.random()&&this.I(new w(g,d))}function v(a,b){n.call(this,a+.5,b+.5);this.v=0;this.R=5}function K(){}function w(a,b){n.call(this,a+.5,b+.5);this.v=0;this.R=100}function B(a,b){n.call(this,a,b);this.M=this.dir=0}function C(a,b){t.call(this,a,b,1,1)}function D(a,b){t.call(this,a,b,3,1)}function t(a,b,c,d){n.call(this,a,b);this.xa=.3*Math.random()-
.15;this.ya=.3*Math.random()-.15;this.pb=c;this.qb=d;this.count=5*Math.random()|0}function E(a,b){n.call(this,a+.5,b+.5)}function h(a){y.call(this,a)}function y(a){this.canvas=a;this.input=new G;this.H=new H;this.l=new A;this.Ya()}function n(a,b){this.x=a;this.y=b;this.count=0}function u(a,b){function c(){}c.prototype=a;a=new c;for(var d in b)a[d]=b[d];b.toString!==Object.prototype.toString&&(a.toString=b.toString);return a}function M(a,b){if(null==b)return null;null==b.la&&(b.la=R++);var c;null==
a.va?a.va={}:c=a.va[b.la];null==c&&(c=function(){return c.method.apply(c.scope,arguments)},c.scope=a,c.method=b,a.va[b.la]=c);return c}n.c=!0;n.prototype={update:function(){},o:function(){},g:n};y.c=!0;y.prototype={Ya:function(){function a(a){a.cancelable&&a.preventDefault();for(var d=0,m=a.changedTouches.length;d<m;){var f=a.changedTouches[d++];if(f.identifier==g){g=-1;var h=f.clientX-c();e.input.X=h*k;f=f.clientY-b();e.input.Y=f*k;e.input.qa=!1}}}function b(){return e.canvas.getBoundingClientRect().top}
function c(){return e.canvas.getBoundingClientRect().left}var d=this;this.h=0;this.Na();if(1!=this.h)throw new l("call init()");this.h=2;var e=this;if(2!=this.h)throw new l("invalid call");var g=-1,k=window.devicePixelRatio/this.ka,f=window.document.body;f.addEventListener("touchstart",function(a){a.cancelable&&a.preventDefault();-1==g&&(g=a.changedTouches[0].identifier);for(var d=0,m=a.changedTouches.length;d<m;){var f=a.changedTouches[d++];if(f.identifier==g){var h=f.clientX-c();e.input.X=h*k;f=
f.clientY-b();e.input.Y=f*k;e.input.qa=!0}}});f.addEventListener("touchmove",function(a){a.cancelable&&a.preventDefault();for(var d=0,f=a.touches.length;d<f;){var m=a.touches[d++];if(m.identifier==g){var h=m.clientX-c();e.input.X=h*k;m=m.clientY-b();e.input.Y=m*k}}});f.addEventListener("touchend",a);f.addEventListener("touchcancel",a);f.addEventListener("mousedown",function(a){a.cancelable&&a.preventDefault();switch(a.button){case 0:e.input.pa=!0;break;case 2:e.input.za=!0}var d=a.clientX-c();e.input.V=
d*k;a=a.clientY-b();e.input.W=a*k});f.addEventListener("mouseup",function(a){a.cancelable&&a.preventDefault();switch(a.button){case 0:e.input.pa=!1;break;case 2:e.input.za=!1}var d=a.clientX-c();e.input.V=d*k;a=a.clientY-b();e.input.W=a*k});f.addEventListener("mousemove",function(a){a.cancelable&&a.preventDefault();var d=a.clientX-c();e.input.V=d*k;a=a.clientY-b();e.input.W=a*k});f.oncontextmenu=function(){return!1};this.H.tb(function(){d.h=3;d.Ia();d.h=4;var a=d.Za;a.Ma=!0;a.Aa=(new Date).getTime();
a.loop()})},Na:function(){throw new l("override this");},Wa:function(){if(4!=this.h)throw new l("invalid call");this.input.$a();this.loop();this.Xa.j(this.buffer,0,0,this.oa,this.U,0,0,this.na,this.ma)},loop:function(){throw new l("override this");},Ia:function(){},g:y};h.c=!0;h.L=function(){new h(window.document.getElementById("canvas"))};h.w=y;h.prototype=u(y.prototype,{Na:function(){h.f=this;var a=window.navigator.userAgent;-1!=a.indexOf("iPad")||-1==a.indexOf("iPhone")&&-1==a.indexOf("Android")||
(a=window.document.createElement("meta"),a.setAttribute("name","viewport"),a.setAttribute("content","width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"),window.document.head.appendChild(a),window.document.body.style.margin="0");var a=window.innerWidth/128,b=window.innerHeight/128;if(0!=this.h)throw new l("invalid call");this.h=1;var c=window.devicePixelRatio;this.ka=(a<b?a:b)*window.devicePixelRatio|0;this.U=this.oa=128;this.buffer=new q(this.oa,this.U,p.D);this.sa=
this.buffer.sa;this.u=this.buffer.u;this.na=this.oa*this.ka;this.ma=this.U*this.ka;this.canvas.style.width=this.na/c+"px";this.canvas.style.height=this.ma/c+"px";this.canvas.width=this.na;this.canvas.height=this.ma;this.Xa=new z(this.canvas.getContext("2d",null));this.Za=new F(50,M(this,this.Wa));this.s=new z(this.u);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="tile.gif";this.l.set("tile.gif",a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src=
"title.gif";this.l.set("title.gif",a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="pl.gif";this.l.set("pl.gif",a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="craft.gif";this.l.set("craft.gif",a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="craftw.gif";this.l.set("craftw.gif",a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="gameover.gif";this.l.set("gameover.gif",
a);this.H.add(a);if(this.h&&1!=this.h)throw new l("invalid call");a=new Image;a.src="text.gif";this.l.set("text.gif",a);this.H.add(a);this.hb()},Ia:function(){var a=this.l.get("tile.gif"),b=a.width,c=a.height,d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.S=d;a=this.l.get("title.gif");b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.rb=d;a=this.l.get("pl.gif");b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.Ja=d;a=this.l.get("craft.gif");
b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.bb=d;a=this.l.get("craftw.gif");b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.aa=d;a=this.l.get("gameover.gif");b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.cb=d;a=this.l.get("text.gif");b=a.width;c=a.height;d=new q(b,c,p.D);d.u.drawImage(a,0,0,b,c,0,0,b,c);this.Oa=d},B:function(a){this.Pa=a;this.C=9>a?50:130},hb:function(){this.ga=this.mode=this.count=0;this.A=
-1;this.items=[0,0,0,0,0,0,0];this.Ga=10;this.G=!1;this.i=new J(16,16);this.b=new B(8,8);this.i.I(this.b)},ub:function(a,b){return a+Math.random()*(b-a)},loop:function(){this.update();this.o()},update:function(){this.count++;switch(this.mode){case 0:this.ga++;1==this.input.P+this.input.O&&(100<this.ga?this.gb():this.ga=100);break;case 1:this.Ha++;0<this.C&&this.C--;9E3<this.Ha&&(this.G=!0);2==this.i.Ca(this.b.x,this.b.y)&&(this.b.y=1E4);100<this.b.y&&(this.b.y+=100);2E4<this.b.y&&this.ta();-100>this.b.y&&
(this.b.y-=100);-3E4>this.b.y&&this.ta();0<this.items[6]&&(this.items[6]=0,this.i.I(new E(this.b.x|0,this.b.y|0)),this.b.y=-1E4);this.control();this.i.update();break;case 2:0<this.C&&this.C--;this.ab();break;case 3:if(this.Ba++,1==this.input.O+this.input.P&&50<this.Ba){var a=0<this.items[1]?"\u30af\u30ed\u30b9\u3092"+this.items[1]+"\u500b\u4f5c\u3063\u3066":0<this.items[2]?"\u30b4\u30df\u3092"+this.items[2]+"\u500b\u751f\u6210\u3057\u3066":"\u4f55\u3082\u3067\u304d\u306a\u3044\u307e\u307e",a=100<
this.b.y?a+(this.G?"\u30be\u30f3\u30d3\u304b\u3089\u9003\u3052\u3088\u3046\u3068\u3057\u3066\u6eba\u308c\u3066\u6b7b\u3093\u3060\u3002 ":"\u6eba\u308c\u3066\u6b7b\u3093\u3060\u3002 "):a+"\u30be\u30f3\u30d3\u306b\u6bba\u3055\u308c\u305f\u3002 ";-100>this.b.y&&(a="\u3064\u3044\u306b\u8f2a\u5efb\u304b\u3089\u89e3\u8131\u3057\u305f\uff01\u304a\u3081\u3067\u3068\u3046\uff01 ");window.location.href="https://twitter.com/intent/tweet?text="+encodeURIComponent(a+window.location.href+" #crosscraft")}}},control:function(){for(var a=
this.input.ia+this.input.da,b=this.input.ja+this.input.ea,c=this.input.ca||this.input.ha,d=this.input.P+this.input.O,e=0,g=this.i.J;e<g.length;){var k=g[e];++e;if(f.f(k,x)){var h=f.$(k,x),m=this.N(this.b,h);if(.8>m&&(k=h.x-this.b.x,h=h.y-this.b.y,m=(1.6-m)/Math.sqrt(k*k+h*h+1E-6),k*=m,h*=m,this.b.x-=k,this.b.y-=h,this.B(4+(5*Math.random()|0)),this.Ga--,0==this.Ga)){this.ta();return}}}if(c)for(c=a/8-this.b.x,k=b/8-this.b.y,m=1/Math.sqrt(c*c+k*k+1E-6),this.b.x+=c*m*.07,this.b.y+=k*m*.07,this.b.dir=
(0<c?c:-c)>(0<k?k:-k)?1:0,this.b.M++,e=0,g=this.i.J;e<g.length;){if(k=g[e],++e,f.f(k,v)||f.f(k,w))m=this.N(this.b,k),.8>m&&(c=k.x-this.b.x,k=k.y-this.b.y,m=(.8-m)/Math.sqrt(c*c+k*k+1E-6),c*=m,k*=m,this.b.x-=c,this.b.y-=k)}else this.b.M=0;if(1==d){d=0;for(c=this.i.J;d<c.length;)e=c[d],++d,f.f(e,v)&&(g=f.$(e,v),.8>this.N(this.b,g)&&1.5>this.ba(g.x,g.y,a/8,b/8)&&(g.ua(),0<this.items[4]?this.B(1):this.B(0))),f.f(e,w)&&(e=f.$(e,w),.8>this.N(this.b,e)&&1.5>this.ba(e.x,e.y,a/8,b/8)&&(0<this.items[4]?(e.ua(),
this.B(3)):this.B(2)));3==this.i.Ca(this.b.x,this.b.y)&&1.5>this.ba(this.b.x,this.b.y,a/8,b/8)&&!this.G&&this.fb()}},ta:function(){this.Ba=this.C=0;this.mode=3},fb:function(){this.C=0;this.mode=2;this.a=[[0,0,0],[0,0,0],[0,0,0]]},ab:function(){var a=this.input.ia+this.input.da,b=this.input.ja+this.input.ea;if(1==this.input.P+this.input.O){for(var c=0;3>c;){c++;for(var d=0;3>d;)d++}if(this.Z(a,b,108,16,16,16)){for(a=0;3>a;)for(b=a++,c=0;3>c;)d=c++,0!=this.a[b][d]&&(this.items[this.a[b][d]-1]++,this.a[b][d]=
0);this.mode=1}else{for(c=0;3>c;)for(var d=c++,e=0;3>e;){var g=e++;this.Z(a,b,24+16*g,56+16*d,16,16)&&(0==this.a[d][g]&&-1!=this.A&&0<this.items[this.A]?(this.a[d][g]=this.A+1,this.items[this.A]--,0==this.items[this.A]&&(this.A=-1)):0!=this.a[d][g]&&(this.items[this.a[d][g]-1]++,this.a[d][g]=0))}for(c=0;6>c;)d=c++,this.Z(a,b,8+16*d,109,16,16)&&0<this.items[d]&&(this.A=this.A==d?-1:d);c=this.Da();if(this.Z(a,b,104,72,16,16))switch(this.items[c]++,this.a=[[0,0,0],[0,0,0],[0,0,0]],c){case 1:this.B(10);
break;case 2:this.B(9);break;case 3:this.B(11);break;case 4:this.B(12);break;case 6:this.B(13)}}}},Da:function(){for(var a=0,b=0;3>b;)for(var c=b++,d=0;3>d;)0!=this.a[c][d++]&&++a;return 0==this.a[0][0]&&1==this.a[0][1]&&0==this.a[0][2]&&1==this.a[1][0]&&1==this.a[1][1]&&1==this.a[1][2]&&0==this.a[2][0]&&1==this.a[2][1]&&0==this.a[2][2]?1:2==a&&(1==this.a[0][0]&&1==this.a[1][0]||1==this.a[0][1]&&1==this.a[1][1]||1==this.a[0][2]&&1==this.a[1][2]||1==this.a[1][0]&&1==this.a[2][0]||1==this.a[1][1]&&
1==this.a[2][1]||1==this.a[1][2]&&1==this.a[2][2])?3:1==this.a[0][0]&&1==this.a[0][1]&&1==this.a[0][2]&&0==this.a[1][0]&&4==this.a[1][1]&&0==this.a[1][2]&&0==this.a[2][0]&&4==this.a[2][1]&&0==this.a[2][2]?4:0==this.a[0][0]&&6==this.a[0][1]&&0==this.a[0][2]&&6==this.a[1][0]&&6==this.a[1][1]&&6==this.a[1][2]&&0==this.a[2][0]&&6==this.a[2][1]&&0==this.a[2][2]?6:0<a?2:-1},Z:function(a,b,c,d,e,g){return a>c&&a<c+e&&b>d?b<d+g:!1},ba:function(a,b,c,d){return Math.sqrt((c-a)*(c-a)+(d-b)*(d-b))},N:function(a,
b){return this.ba(a.x,a.y,b.x,b.y)},gb:function(){this.Ha=0;this.mode=1},o:function(){var a=this.s,b=a.m.fillStyle;a.m.fillStyle="rgb(0,0,0)";a.m.fillRect(0,0,a.m.canvas.width,a.m.canvas.height);a.m.fillStyle=b;switch(this.mode){case 0:this.i.o(this.s);a=-32+(this.ga>>1);24<a&&(a=24);this.s.j(this.rb,0,0,128,32,0,a,128,32);break;case 1:this.i.o(this.s);0<this.C&&this.s.j(this.Oa,0,16*this.Pa,128,16,0,(49<=this.C?-1:0)+(this.b.y>.8*this.i.K?0:this.U-16),128,16);break;case 2:this.s.j(this.bb,0,0,128,
128,0,0,128,128);for(a=0;3>a;)for(var b=a++,c=0;3>c;){var d=c++;0!=this.a[b][d]&&this.s.j(this.aa,16*(this.a[b][d]-1),0,16,16,24+16*d,56+16*b,16,16)}for(a=0;7>a;)b=a++,0<this.items[b]&&this.s.j(this.aa,16*b,0,16,16,8+16*b,109,16,16);a=this.Da();-1!=a&&this.s.j(this.aa,16*a,0,16,16,104,72,16,16);-1!=this.A&&this.s.j(this.aa,16*this.A,0,16,16,this.input.ia+this.input.da-8,this.input.ja+this.input.ea-8,16,16);0<this.C&&this.s.j(this.Oa,0,16*this.Pa,128,16,0,129<=this.C?-1:0,128,16);break;case 3:this.s.j(this.cb,
0,0,128,32,0,32,128,32)}},g:h});E.c=!0;E.w=n;E.prototype=u(n.prototype,{update:function(){},o:function(a){a.j(h.f.S,32,0,16,16,Math.round(8*this.x)-8,Math.round(8*this.y)-8,16,16)},g:E});t.c=!0;t.w=n;t.prototype=u(n.prototype,{update:function(){this.xa*=.9;this.ya*=.9;this.x+=this.xa;this.y+=this.ya;this.count++;.8>h.f.N(this,h.f.b)&&50<this.count&&this.wa()},wa:function(){},o:function(a){50>this.count&&!((this.count>>1)%2)||a.j(h.f.S,8*this.pb,8*this.qb+(h.f.G?16:0),8,8,Math.round(8*this.x)-4,Math.round(8*
this.y)-4,8,8)},g:t});D.c=!0;D.w=t;D.prototype=u(t.prototype,{wa:function(){this.remove=!0;h.f.items[5]++},g:D});C.c=!0;C.w=t;C.prototype=u(t.prototype,{wa:function(){this.remove=!0;h.f.items[0]++},g:C});Math.c=!0;B.c=!0;B.w=n;B.prototype=u(n.prototype,{update:function(){},o:function(a){a.j(h.f.Ja,(this.M>>1)%4*8,8*this.dir,8,8,Math.round(8*this.x)-4,Math.round(8*this.y)-4,8,8)},g:B});w.c=!0;w.w=n;w.prototype=u(n.prototype,{update:function(){0<this.v&&this.v--},ua:function(){this.v=10;this.R--;0==
this.R&&(this.remove=!0,h.f.i.I(new D(this.x,this.y)))},o:function(a){a.j(h.f.S,16,8+(h.f.G?16:0),8,8,Math.round(8*this.x+(0<this.v?2*Math.random()-1:0))-4,Math.round(8*this.y+(0<this.v?2*Math.random()-1:0))-4,8,8)},g:w});K.c=!0;K.Fa=function(a){return f.L(a,"")};v.c=!0;v.w=n;v.prototype=u(n.prototype,{update:function(){0<this.v&&this.v--},ua:function(){this.v=10;this.R--;if(0==this.R){this.remove=!0;for(var a=Math.random()*Math.random()*3+1|0,b=0;b<a;)++b,h.f.i.I(new C(this.x,this.y))}},o:function(a){a.j(h.f.S,
0,8+(h.f.G?16:0),8,8,Math.round(8*this.x+(0<this.v?2*Math.random()-1:0))-4,Math.round(8*this.y+(0<this.v?2*Math.random()-1:0))-4,8,8)},g:v});J.c=!0;J.prototype={update:function(){for(var a=0,b=this.J;a<b.length;){var c=b[a];++a;c.update()}this.J=this.J.filter(function(a){return!a.remove});this.count++;if(!(h.f.G||this.count%500))for(a=0,b=this.K;a<b;)for(var c=a++,d=0,e=this.i;d<e;){var g=d++;0==this.data[c][g]&&.01>Math.random()&&this.I(new v(g,c))}if(h.f.G&&!(this.count%20))for(a=0,b=this.K;a<b;)for(c=
a++,d=0,e=this.i;d<e;)g=d++,0==this.data[c][g]&&.005>Math.random()&&this.I(new x(g,c))},o:function(a){for(var b=h.f.S,c=0,d=this.K;c<d;)for(var e=c++,g=0,f=this.i;g<f;){var l=g++;a.j(b,8*this.data[e][l],h.f.G?16:0,8,8,8*l,8*e,8,8)}b=0;for(c=this.J;b<c.length;)d=c[b],++b,d.o(a)},I:function(a){this.J.push(a)},Ca:function(a,b){a|=0;b|=0;return 0<=a&&a<this.i&&0<=b&&b<this.K?this.data[b][a]:-1},g:J};x.c=!0;x.w=n;x.prototype=u(n.prototype,{update:function(){var a=h.f.b,b=a.x-this.x,a=a.y-this.y,c=1/Math.sqrt(b*
b+a*a+1E-6);this.x+=b*c*.05;this.y+=a*c*.05;this.dir=Math.abs(b)>Math.abs(a)?1:0;this.M++},o:function(a){a.j(h.f.Ja,(this.M>>1)%4*8,16+8*this.dir,8,8,Math.round(8*this.x)-4,Math.round(8*this.y)-4,8,8)},g:x});I.c=!0;I.prototype={g:I};A.c=!0;A.Va=[I];A.prototype={set:function(a,b){null!=N[a]?this.mb(a,b):this.K[a]=b},get:function(a){return null!=N[a]?this.eb(a):this.K[a]},mb:function(a,b){null==this.fa&&(this.fa={});this.fa["$"+a]=b},eb:function(a){return null==this.fa?null:this.fa["$"+a]},g:A};l.c=
!0;l.$=function(a){return a instanceof Error?a:new l(a)};l.w=Error;l.prototype=u(Error.prototype,{g:l});f.c=!0;f.lb=function(a){if(a instanceof Array&&null==a.F)return Array;var b=a.g;if(null!=b)return b;a=f.Ea(a);return null!=a?f.jb(a):null};f.L=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.c||a.T)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof Array){if(a.F){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";
for(var d=2,e=a.length;d<e;)var g=d++,c=2!=g?c+(","+f.L(a[g],b)):c+f.L(a[g],b);return c+")"}c=a.length;d="[";b+="\t";for(e=0;e<c;)g=e++,d+=(0<g?",":"")+f.L(a[g],b);return d+"]"}try{d=a.toString}catch(k){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(c=a.toString(),"[object Object]"!=c))return c;c=null;d="{\n";b+="\t";e=null!=a.hasOwnProperty;for(c in a)e&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=d.length&&
(d+=", \n"),d+=b+c+" : "+f.L(a[c],b));b=b.substring(1);return d+("\n"+b+"}");case "string":return a;default:return String(a)}};f.ra=function(a,b){if(null==a)return!1;if(a==b)return!0;var c=a.Va;if(null!=c)for(var d=0,e=c.length;d<e;){var g=c[d++];if(g==b||f.ra(g,b))return!0}return f.ra(a.w,b)};f.f=function(a,b){if(null==b)return!1;switch(b){case Array:return a instanceof Array?null==a.F:!1;case O:return"boolean"==typeof a;case S:return!0;case P:return"number"==typeof a;case T:return"number"==typeof a?
(a|0)===a:!1;case String:return"string"==typeof a;default:if(null!=a)if("function"==typeof b){if(a instanceof b||f.ra(f.lb(a),b))return!0}else{if("object"==typeof b&&f.ib(b)&&a instanceof b)return!0}else return!1;return b==U&&null!=a.c||b==V&&null!=a.T?!0:a.F==b}};f.$=function(a,b){if(f.f(a,b))return a;throw new l("Cannot cast "+K.Fa(a)+" to "+K.Fa(b));};f.Ea=function(a){a=f.kb.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};f.ib=function(a){return null!=f.Ea(a)};
f.jb=function(a){return Q[a]};L.c=!0;L.sb=function(a){for(var b=0,c=["webgl","experimental-webgl"];b<c.length;){var d=c[b];++b;d=a.getContext(d,null);if(null!=d)return d}return null};var r={T:!0,Ua:["Blend","Add","Multiply","Screen"],Ra:["Blend",0]};r.Ra.F=r;r.Qa=["Add",1];r.Qa.F=r;r.Sa=["Multiply",2];r.Sa.F=r;r.Screen=["Screen",3];r.Screen.F=r;var p={T:!0,Ua:["WebGL","Canvas2D"],Ta:["WebGL",0]};p.Ta.F=p;p.D=["Canvas2D",1];p.D.F=p;H.c=!0;H.prototype={add:function(a){this.images.push(a)},tb:function(a){var b=
this.images.length;if(0==b)a();else for(var c=0,d=this.images;c<d.length;){var e=d[c];++c;e.onload=function(){0==--b&&a()}}},g:H};G.c=!0;G.prototype={$a:function(){this.ia=this.X;this.ja=this.Y;this.La=this.ha;this.ha=this.qa;this.P=(this.ha?1:0)-(this.La?1:0);this.da=this.V;this.ea=this.W;this.Ka=this.ca;this.ca=this.pa;this.O=(this.ca?1:0)-(this.Ka?1:0)},g:G};F.c=!0;F.prototype={loop:function(){this.ob();var a=(new Date).getTime(),b=this.Aa+1E3/this.nb-a;5>b&&(b=5);this.Aa=a+b;this.Ma&&window.setTimeout(M(this,
this.loop),b+.5|0)},g:F};z.c=!0;z.prototype={fill:function(a,b,c,d){null==d&&(d=1);this.m.fillStyle="rgba("+(255*a+.5|0)+","+(255*b+.5|0)+","+(255*c+.5|0)+","+d+")"},stroke:function(a,b,c,d){null==d&&(d=1);this.m.strokeStyle="rgba("+(255*a+.5|0)+","+(255*b+.5|0)+","+(255*c+.5|0)+","+d+")"},push:function(){this.m.save()},scale:function(a,b){this.m.scale(a,b)},translate:function(a,b){this.m.translate(a,b)},j:function(a,b,c,d,e,f,h,l,m){this.m.imageSmoothingEnabled=!1;this.m.msImageSmoothingEnabled=
!1;this.m.drawImage(a.canvas,b,c,d,e,f,h,l,m)},g:z};q.c=!0;q.prototype={g:q};var R=0;String.prototype.g=String;String.c=!0;Array.c=!0;Date.prototype.g=Date;Date.c=["Date"];var T={c:["Int"]},S={c:["Dynamic"]},P=Number;P.c=["Float"];var O=Boolean;O.T=["Bool"];var U={c:["Class"]},V={},N={};f.kb={}.toString;h.L()})("undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
